spring.application.name=cliente service

server.port=8081

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:clientedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HABILITAR LA CONSOLA (Para que puedas ver la DB en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console